### ISSUE TITLE
Carl's WGLC review

### ISSUE THREAD

**Issue by thomas-fossati** [dthaler/rats-endorsements#39]
@carl-wallace [review](https://mailarchive.ietf.org/arch/msg/rats/I1ZTK_p-dQTHEssBZB6-md8Chaw/):

* [ ] _"[...] I think it may benefit from a bit more discussion on how trust is established in endorsements and how the binding from endorsements to target environment is established. There is no mention of either in the security considerations section. RFC 9334 defines endorsements as being a “secure statement”, so piggybacking off that definition to reference some (abstract) state that must be present in the verifier to verify the endorsement may suffice."_
 
* [ ] _"Commenting on the need (or lack of need) for timeliness of endorsements may be worthwhile as well. There is discussion of actual state relative to points in time but not how endorsements fit on the timeline."_
 
* [ ] _"One nit, section 5 states the following: “The binding between Target Environment and Endorser might be part of the Appraisal Policy for Evidence, or might be specified as part of the Evidence itself (e.g., claims from a Target Environment might include a secure identifier of what Endorser can provide additional claims about it), or some combination of the two.“ Given the evidence has not yet been verified, referring to the identifier as a “secure identifier” is probably not appropriate."_

**Comment by dthaler** [comment]
Fixed in draft -05 and presented at IETF 121
