### ISSUE TITLE
Kathleen's WGLC comments

### ISSUE THREAD

**Issue by thomas-fossati** [dthaler/rats-endorsements#40]
@KME [review](https://mailarchive.ietf.org/arch/msg/rats/A9ufARyqbjBnBAEA0lmZPwRTUic/)

> _"[...] wondering if there are additional security considerations on the layers, differing sources for policies mentioned in the draft, and formats for developers or implementers."_

**Comment by dthaler** [comment]
Fixed in draft -05 and presented at IETF
